--- #YAML:1.0
name:                Apache-SizeLimit
version:             0.91
abstract:            Because size does matter.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    mod_perl:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
