# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-SizeLimit
version:      0.9
version_from: lib/Apache/SizeLimit.pm
installdirs:  site
requires:
    mod_perl:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
